version: 2.1

executors:
  docker:
    working_directory: /tmp/workspace
    docker:
      - image: docker:latest

jobs:
  docker:
    parameters:
      deploy:
        type: boolean
        default: false
      path:
        type: string
        default: "docker"
      tag:
        type: string
        default: "docker"
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Checkout submodule
          command: |
            apk add --no-cache git
            git submodule update --init --recursive
      - run:
          name: Build
          command: |
            docker build -t misskey/ci:<<parameters.tag>> <<parameters.path>>
      - when:
          condition: <<parameters.deploy>>
          steps:
            - run:
                name: Deploy
                command: |
                  if [ "$DOCKERHUB_USERNAME$DOCKERHUB_PASSWORD" ]
                  then
                    docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
                    docker push misskey/ci:<<parameters.tag>>
                  else
                    echo -e '\033[0;33mDeploy Aborted\033[0;39m'
                  fi

workflows:
  version: 2
  v11-node12:
    jobs:
      - docker:
          name: build-v11-node12
          path: v11/node12
          tag: v11-node12
          filters:
            branches:
              ignore: master
      - docker:
          name: deploy-v11-node12
          deploy: true
          path: v11/node12
          tag: v11-node12
          filters:
            branches:
              only: master
  v11-node11:
    jobs:
      - docker:
          name: build-v11-node11
          path: v11/node11
          tag: v11-node11
          filters:
            branches:
              ignore: master
      - docker:
          name: deploy-v11-node11
          deploy: true
          path: v11/node11
          tag: v11-node11
          filters:
            branches:
              only: master
  v10-node11:
    jobs:
      - docker:
          name: build-v10-node11
          path: v10/node11
          tag: v10-node11
          filters:
            branches:
              ignore: master
      - docker:
          name: deploy-v10-node11
          deploy: true
          path: v10/node11
          tag: v10-node11
          filters:
            branches:
              only: master
  v10-node10:
    jobs:
      - docker:
          name: build-v10-node10
          path: v10/node10
          tag: v10-node10
          filters:
            branches:
              ignore: master
      - docker:
          name: deploy-v10-node10
          deploy: true
          path: v10/node10
          tag: v10-node10
          filters:
            branches:
              only: master
  docker:
    jobs:
      - docker:
          name: build-docker
          path: docker
          tag: docker
          filters:
            branches:
              ignore: master
      - docker:
          name: deploy-docker
          deploy: true
          path: docker
          tag: docker
          filters:
            branches:
              only: master
