version: 2.1

executors:
  docker:
    working_directory: /tmp/workspace
    docker:
      - image: docker:latest

jobs:
  build:
    parameters:
      path:
        type: string
        default: "docker"
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            docker build -t misskey/ci <<parameters.path>>
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    parameters:
      tag:
        type: string
        default: "docker"
    executor: docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy
          command: |
            if [ "$DOCKERHUB_USERNAME$DOCKERHUB_PASSWORD" ]
             then
              docker tag misskey/ci misskey/ci:<<parameters.tag>>
              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
              docker push misskey/ci:<<parameters.tag>>
             else
              echo -e '\033[0;33mAborted deploying to Docker Hub\033[0;39m'
            fi

workflows:
  version: 2
  v11-node11:
    jobs:
      - build:
          name: build
          path: v11/node11
      - deploy:
          name: deploy
          tag: v11-node11
          requires:
            - build
          filters:
            branches:
              only: master
  v11-node8:
    jobs:
      - build:
          name: build
          path: v11/node8
      - deploy:
          name: deploy
          tag: v11-node8
          requires:
            - build
          filters:
            branches:
              only: master
  v10-node11:
    jobs:
      - build:
          name: build
          path: v10/node11
      - deploy:
          name: deploy
          tag: v10-node11
          requires:
            - build
          filters:
            branches:
              only: master
  v10-node8:
    jobs:
      - build:
          name: build
          path: v10/node8
      - deploy:
          name: deploy
          tag: v10-node8
          requires:
            - build
          filters:
            branches:
              only: master
  docker:
    jobs:
      - build:
          name: build
          path: docker
      - deploy:
          name: deploy
          tag: docker
          requires:
            - build
          filters:
            branches:
              only: master
