version: 2.1

executors:
  docker:
    working_directory: /tmp/workspace
    docker:
      - image: docker:latest

jobs:
  build:
    parameters:
      path:
        type: string
        default: "docker"
      tag:
        type: string
        default: "docker"
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build
          command: |
            docker build -t misskey/ci:<<parameters.tag>> <<parameters.path>>
  deploy:
    parameters:
      path:
        type: string
        default: "docker"
      tag:
        type: string
        default: "docker"
    executor: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build
          command: |
            docker build -t misskey/ci:<<parameters.tag>> <<parameters.path>>
      - run:
          name: Deploy
          command: |
            if [ "$DOCKERHUB_USERNAME$DOCKERHUB_PASSWORD" ]
             then
              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
              docker push misskey/ci
             else
              echo -e '\033[0;33mDeploy Aborted\033[0;39m'
            fi

workflows:
  version: 2
  v11-node11:
    jobs:
      - build:
          name: build
          path: v11/node11
          tag: v11-node11
          filters:
            branches:
              ignore: master
      - deploy:
          name: deploy
          path: v11/node11
          tag: v11-node11
          filters:
            branches:
              only: master
  v11-node8:
    jobs:
      - build:
          name: build
          path: v11/node8
          tag: v11-node8
          filters:
            branches:
              ignore: master
      - deploy:
          name: deploy
          path: v11/node8
          tag: v11-node8
          filters:
            branches:
              only: master
  v10-node11:
    jobs:
      - build:
          name: build
          path: v10/node11
          tag: v10-node11
          filters:
            branches:
              ignore: master
      - deploy:
          name: deploy
          path: v10/node11
          tag: v10-node11
          filters:
            branches:
              only: master
  v10-node8:
    jobs:
      - build:
          name: build
          path: v10/node8
          tag: v10-node8
          filters:
            branches:
              ignore: master
      - deploy:
          name: deploy
          path: v10/node8
          tag: v10-node8
          filters:
            branches:
              only: master
  docker:
    jobs:
      - build:
          name: build
          path: docker
          tag: docker
          filters:
            branches:
              ignore: master
      - deploy:
          name: deploy
          path: docker
          tag: docker
          filters:
            branches:
              only: master
